services:
  app:
    build: app/
    command: python app.py
    ports: 8080:8080

  test:
    build: Test/
    command: python -m pytest -vv test_app.py
    network_mode: host

    depends_on:
      - app